let className = document.getElementById("class-name").innerText
console.log(className)
let level = document.getElementById("level")
let class1 = document.getElementById(`${className}1`)
let class2 = document.getElementById(`${className}2`)
let class3 = document.getElementById(`${className}3`)
let class4 = document.getElementById(`${className}4`)
let class5 = document.getElementById(`${className}5`)
let class6 = document.getElementById(`${className}6`)
let class7 = document.getElementById(`${className}7`)
let class8 = document.getElementById(`${className}8`)
let class9 = document.getElementById(`${className}9`)
let class10 = document.getElementById(`${className}10`)
let class11 = document.getElementById(`${className}11`)
let class12 = document.getElementById(`${className}12`)
let class13 = document.getElementById(`${className}13`)
let class14 = document.getElementById(`${className}14`)
let class15 = document.getElementById(`${className}15`)
let class16 = document.getElementById(`${className}16`)
let class17 = document.getElementById(`${className}17`)
let class18 = document.getElementById(`${className}18`)
let class19 = document.getElementById(`${className}19`)
let class20 = document.getElementById(`${className}20`)

switch (level.innerText) {
    case "19":
        class1.style.backgroundColor = "#fefcdb66"
        class2.style.backgroundColor = "#fefcdb66"
        class3.style.backgroundColor = "#fefcdb66"
        class4.style.backgroundColor = "#fefcdb66"
        class5.style.backgroundColor = "#fefcdb66"
        class6.style.backgroundColor = "#fefcdb66"
        class7.style.backgroundColor = "#fefcdb66"
        class8.style.backgroundColor = "#fefcdb66"
        class9.style.backgroundColor = "#fefcdb66"
        class10.style.backgroundColor = "#fefcdb66"
        class11.style.backgroundColor = "#fefcdb66"
        class12.style.backgroundColor = "#fefcdb66"
        class13.style.backgroundColor = "#fefcdb66"
        class14.style.backgroundColor = "#fefcdb66"
        class15.style.backgroundColor = "#fefcdb66"
        class16.style.backgroundColor = "#fefcdb66"
        class17.style.backgroundColor = "#fefcdb66"
        class18.style.backgroundColor = "#fefcdb66"
        class19.style.backgroundColor = "#fefcdb66"

        class1.style.color = "black"
        class2.style.color = "black"
        class3.style.color = "black"
        class4.style.color = "black"
        class5.style.color = "black"
        class6.style.color = "black"
        class7.style.color = "black"
        class8.style.color = "black"
        class9.style.color = "black"
        class10.style.color = "black"
        class11.style.color = "black"
        class12.style.color = "black"
        class13.style.color = "black"
        class14.style.color = "black"
        class15.style.color = "black"
        class16.style.color = "black"
        class17.style.color = "black"
        class18.style.color = "black"
        class19.style.color = "black"
        break
    case "18":
        class1.style.backgroundColor = "#fefcdb66"
        class2.style.backgroundColor = "#fefcdb66"
        class3.style.backgroundColor = "#fefcdb66"
        class4.style.backgroundColor = "#fefcdb66"
        class5.style.backgroundColor = "#fefcdb66"
        class6.style.backgroundColor = "#fefcdb66"
        class7.style.backgroundColor = "#fefcdb66"
        class8.style.backgroundColor = "#fefcdb66"
        class9.style.backgroundColor = "#fefcdb66"
        class10.style.backgroundColor = "#fefcdb66"
        class11.style.backgroundColor = "#fefcdb66"
        class12.style.backgroundColor = "#fefcdb66"
        class13.style.backgroundColor = "#fefcdb66"
        class14.style.backgroundColor = "#fefcdb66"
        class15.style.backgroundColor = "#fefcdb66"
        class16.style.backgroundColor = "#fefcdb66"
        class17.style.backgroundColor = "#fefcdb66"
        class18.style.backgroundColor = "#fefcdb66"

        class1.style.color = "black"
        class2.style.color = "black"
        class3.style.color = "black"
        class4.style.color = "black"
        class5.style.color = "black"
        class6.style.color = "black"
        class7.style.color = "black"
        class8.style.color = "black"
        class9.style.color = "black"
        class10.style.color = "black"
        class11.style.color = "black"
        class12.style.color = "black"
        class13.style.color = "black"
        class14.style.color = "black"
        class15.style.color = "black"
        class16.style.color = "black"
        class17.style.color = "black"
        class18.style.color = "black"
        break
    case "17":
        class1.style.backgroundColor = "#fefcdb66"
        class2.style.backgroundColor = "#fefcdb66"
        class3.style.backgroundColor = "#fefcdb66"
        class4.style.backgroundColor = "#fefcdb66"
        class5.style.backgroundColor = "#fefcdb66"
        class6.style.backgroundColor = "#fefcdb66"
        class7.style.backgroundColor = "#fefcdb66"
        class8.style.backgroundColor = "#fefcdb66"
        class9.style.backgroundColor = "#fefcdb66"
        class10.style.backgroundColor = "#fefcdb66"
        class11.style.backgroundColor = "#fefcdb66"
        class12.style.backgroundColor = "#fefcdb66"
        class13.style.backgroundColor = "#fefcdb66"
        class14.style.backgroundColor = "#fefcdb66"
        class15.style.backgroundColor = "#fefcdb66"
        class16.style.backgroundColor = "#fefcdb66"
        class17.style.backgroundColor = "#fefcdb66"

        class1.style.color = "black"
        class2.style.color = "black"
        class3.style.color = "black"
        class4.style.color = "black"
        class5.style.color = "black"
        class6.style.color = "black"
        class7.style.color = "black"
        class8.style.color = "black"
        class9.style.color = "black"
        class10.style.color = "black"
        class11.style.color = "black"
        class12.style.color = "black"
        class13.style.color = "black"
        class14.style.color = "black"
        class15.style.color = "black"
        class16.style.color = "black"
        class17.style.color = "black"
        break
    case "16":
        class1.style.backgroundColor = "#fefcdb66"
        class2.style.backgroundColor = "#fefcdb66"
        class3.style.backgroundColor = "#fefcdb66"
        class4.style.backgroundColor = "#fefcdb66"
        class5.style.backgroundColor = "#fefcdb66"
        class6.style.backgroundColor = "#fefcdb66"
        class7.style.backgroundColor = "#fefcdb66"
        class8.style.backgroundColor = "#fefcdb66"
        class9.style.backgroundColor = "#fefcdb66"
        class10.style.backgroundColor = "#fefcdb66"
        class11.style.backgroundColor = "#fefcdb66"
        class12.style.backgroundColor = "#fefcdb66"
        class13.style.backgroundColor = "#fefcdb66"
        class14.style.backgroundColor = "#fefcdb66"
        class15.style.backgroundColor = "#fefcdb66"
        class16.style.backgroundColor = "#fefcdb66"

        class1.style.color = "black"
        class2.style.color = "black"
        class3.style.color = "black"
        class4.style.color = "black"
        class5.style.color = "black"
        class6.style.color = "black"
        class7.style.color = "black"
        class8.style.color = "black"
        class9.style.color = "black"
        class10.style.color = "black"
        class11.style.color = "black"
        class12.style.color = "black"
        class13.style.color = "black"
        class14.style.color = "black"
        class15.style.color = "black"
        class16.style.color = "black"
        break
    case "15":
        class1.style.backgroundColor = "#fefcdb66"
        class2.style.backgroundColor = "#fefcdb66"
        class3.style.backgroundColor = "#fefcdb66"
        class4.style.backgroundColor = "#fefcdb66"
        class5.style.backgroundColor = "#fefcdb66"
        class6.style.backgroundColor = "#fefcdb66"
        class7.style.backgroundColor = "#fefcdb66"
        class8.style.backgroundColor = "#fefcdb66"
        class9.style.backgroundColor = "#fefcdb66"
        class10.style.backgroundColor = "#fefcdb66"
        class11.style.backgroundColor = "#fefcdb66"
        class12.style.backgroundColor = "#fefcdb66"
        class13.style.backgroundColor = "#fefcdb66"
        class14.style.backgroundColor = "#fefcdb66"
        class15.style.backgroundColor = "#fefcdb66"

        class1.style.color = "black"
        class2.style.color = "black"
        class3.style.color = "black"
        class4.style.color = "black"
        class5.style.color = "black"
        class6.style.color = "black"
        class7.style.color = "black"
        class8.style.color = "black"
        class9.style.color = "black"
        class10.style.color = "black"
        class11.style.color = "black"
        class12.style.color = "black"
        class13.style.color = "black"
        class14.style.color = "black"
        class15.style.color = "black"
        break
    case "14":
        class1.style.backgroundColor = "#fefcdb66"
        class2.style.backgroundColor = "#fefcdb66"
        class3.style.backgroundColor = "#fefcdb66"
        class4.style.backgroundColor = "#fefcdb66"
        class5.style.backgroundColor = "#fefcdb66"
        class6.style.backgroundColor = "#fefcdb66"
        class7.style.backgroundColor = "#fefcdb66"
        class8.style.backgroundColor = "#fefcdb66"
        class9.style.backgroundColor = "#fefcdb66"
        class10.style.backgroundColor = "#fefcdb66"
        class11.style.backgroundColor = "#fefcdb66"
        class12.style.backgroundColor = "#fefcdb66"
        class13.style.backgroundColor = "#fefcdb66"
        class14.style.backgroundColor = "#fefcdb66"

        class1.style.color = "black"
        class2.style.color = "black"
        class3.style.color = "black"
        class4.style.color = "black"
        class5.style.color = "black"
        class6.style.color = "black"
        class7.style.color = "black"
        class8.style.color = "black"
        class9.style.color = "black"
        class10.style.color = "black"
        class11.style.color = "black"
        class12.style.color = "black"
        class13.style.color = "black"
        class14.style.color = "black"
        break
    case "13":
        class1.style.backgroundColor = "#fefcdb66"
        class2.style.backgroundColor = "#fefcdb66"
        class3.style.backgroundColor = "#fefcdb66"
        class4.style.backgroundColor = "#fefcdb66"
        class5.style.backgroundColor = "#fefcdb66"
        class6.style.backgroundColor = "#fefcdb66"
        class7.style.backgroundColor = "#fefcdb66"
        class8.style.backgroundColor = "#fefcdb66"
        class9.style.backgroundColor = "#fefcdb66"
        class10.style.backgroundColor = "#fefcdb66"
        class11.style.backgroundColor = "#fefcdb66"
        class12.style.backgroundColor = "#fefcdb66"
        class13.style.backgroundColor = "#fefcdb66"

        class1.style.color = "black"
        class2.style.color = "black"
        class3.style.color = "black"
        class4.style.color = "black"
        class5.style.color = "black"
        class6.style.color = "black"
        class7.style.color = "black"
        class8.style.color = "black"
        class9.style.color = "black"
        class10.style.color = "black"
        class11.style.color = "black"
        class12.style.color = "black"
        class13.style.color = "black"
        break
    case "12":
        class1.style.backgroundColor = "#fefcdb66"
        class2.style.backgroundColor = "#fefcdb66"
        class3.style.backgroundColor = "#fefcdb66"
        class4.style.backgroundColor = "#fefcdb66"
        class5.style.backgroundColor = "#fefcdb66"
        class6.style.backgroundColor = "#fefcdb66"
        class7.style.backgroundColor = "#fefcdb66"
        class8.style.backgroundColor = "#fefcdb66"
        class9.style.backgroundColor = "#fefcdb66"
        class10.style.backgroundColor = "#fefcdb66"
        class11.style.backgroundColor = "#fefcdb66"
        class12.style.backgroundColor = "#fefcdb66"

        class1.style.color = "black"
        class2.style.color = "black"
        class3.style.color = "black"
        class4.style.color = "black"
        class5.style.color = "black"
        class6.style.color = "black"
        class7.style.color = "black"
        class8.style.color = "black"
        class9.style.color = "black"
        class10.style.color = "black"
        class11.style.color = "black"
        class12.style.color = "black"
        break
    case "11":
        class1.style.backgroundColor = "#fefcdb66"
        class2.style.backgroundColor = "#fefcdb66"
        class3.style.backgroundColor = "#fefcdb66"
        class4.style.backgroundColor = "#fefcdb66"
        class5.style.backgroundColor = "#fefcdb66"
        class6.style.backgroundColor = "#fefcdb66"
        class7.style.backgroundColor = "#fefcdb66"
        class8.style.backgroundColor = "#fefcdb66"
        class9.style.backgroundColor = "#fefcdb66"
        class10.style.backgroundColor = "#fefcdb66"
        class11.style.backgroundColor = "#fefcdb66"

        class1.style.color = "black"
        class2.style.color = "black"
        class3.style.color = "black"
        class4.style.color = "black"
        class5.style.color = "black"
        class6.style.color = "black"
        class7.style.color = "black"
        class8.style.color = "black"
        class9.style.color = "black"
        class10.style.color = "black"
        class11.style.color = "black"
        break
    case "10":
        class1.style.backgroundColor = "#fefcdb66"
        class2.style.backgroundColor = "#fefcdb66"
        class3.style.backgroundColor = "#fefcdb66"
        class4.style.backgroundColor = "#fefcdb66"
        class5.style.backgroundColor = "#fefcdb66"
        class6.style.backgroundColor = "#fefcdb66"
        class7.style.backgroundColor = "#fefcdb66"
        class8.style.backgroundColor = "#fefcdb66"
        class9.style.backgroundColor = "#fefcdb66"
        class10.style.backgroundColor = "#fefcdb66"

        class1.style.color = "black"
        class2.style.color = "black"
        class3.style.color = "black"
        class4.style.color = "black"
        class5.style.color = "black"
        class6.style.color = "black"
        class7.style.color = "black"
        class8.style.color = "black"
        class9.style.color = "black"
        class10.style.color = "black"
        break
    case "9":
        class1.style.backgroundColor = "#fefcdb66"
        class2.style.backgroundColor = "#fefcdb66"
        class3.style.backgroundColor = "#fefcdb66"
        class4.style.backgroundColor = "#fefcdb66"
        class5.style.backgroundColor = "#fefcdb66"
        class6.style.backgroundColor = "#fefcdb66"
        class7.style.backgroundColor = "#fefcdb66"
        class8.style.backgroundColor = "#fefcdb66"
        class9.style.backgroundColor = "#fefcdb66"

        class1.style.color = "black"
        class2.style.color = "black"
        class3.style.color = "black"
        class4.style.color = "black"
        class5.style.color = "black"
        class6.style.color = "black"
        class7.style.color = "black"
        class8.style.color = "black"
        class9.style.color = "black"
        break
    case "8":
        class1.style.backgroundColor = "#fefcdb66"
        class2.style.backgroundColor = "#fefcdb66"
        class3.style.backgroundColor = "#fefcdb66"
        class4.style.backgroundColor = "#fefcdb66"
        class5.style.backgroundColor = "#fefcdb66"
        class6.style.backgroundColor = "#fefcdb66"
        class7.style.backgroundColor = "#fefcdb66"
        class8.style.backgroundColor = "#fefcdb66"

        class1.style.color = "black"
        class2.style.color = "black"
        class3.style.color = "black"
        class4.style.color = "black"
        class5.style.color = "black"
        class6.style.color = "black"
        class7.style.color = "black"
        class8.style.color = "black"
        break
    case "7":
        class1.style.backgroundColor = "#fefcdb66"
        class2.style.backgroundColor = "#fefcdb66"
        class3.style.backgroundColor = "#fefcdb66"
        class4.style.backgroundColor = "#fefcdb66"
        class5.style.backgroundColor = "#fefcdb66"
        class6.style.backgroundColor = "#fefcdb66"
        class7.style.backgroundColor = "#fefcdb66"

        class1.style.color = "black"
        class2.style.color = "black"
        class3.style.color = "black"
        class4.style.color = "black"
        class5.style.color = "black"
        class6.style.color = "black"
        class7.style.color = "black"
        break
    case "6":
        class1.style.backgroundColor = "#fefcdb66"
        class2.style.backgroundColor = "#fefcdb66"
        class3.style.backgroundColor = "#fefcdb66"
        class4.style.backgroundColor = "#fefcdb66"
        class5.style.backgroundColor = "#fefcdb66"
        class6.style.backgroundColor = "#fefcdb66"

        class1.style.color = "black"
        class2.style.color = "black"
        class3.style.color = "black"
        class4.style.color = "black"
        class5.style.color = "black"
        class6.style.color = "black"
        break
    case "5":
        class1.style.backgroundColor = "#fefcdb66"
        class2.style.backgroundColor = "#fefcdb66"
        class3.style.backgroundColor = "#fefcdb66"
        class4.style.backgroundColor = "#fefcdb66"
        class5.style.backgroundColor = "#fefcdb66"

        class1.style.color = "black"
        class2.style.color = "black"
        class3.style.color = "black"
        class4.style.color = "black"
        class5.style.color = "black"
    case "4":
        class1.style.backgroundColor = "#fefcdb66"
        class2.style.backgroundColor = "#fefcdb66"
        class3.style.backgroundColor = "#fefcdb66"
        class4.style.backgroundColor = "#fefcdb66"

        class1.style.color = "black"
        class2.style.color = "black"
        class3.style.color = "black"
        class4.style.color = "black"
        break;
    case "3":
        class1.style.backgroundColor = "#fefcdb66"
        class2.style.backgroundColor = "#fefcdb66"
        class3.style.backgroundColor = "#fefcdb66"

        class1.style.color = "black"
        class2.style.color = "black"
        class3.style.color = "black"
        break;
    case "2":
        class1.style.backgroundColor = "#fefcdb66"
        class2.style.backgroundColor = "#fefcdb66"

        class1.style.color = "black"
        class2.style.color = "black"
        break
    case "1":
        class1.style.backgroundColor = "#fefcdb66"

        class1.style.color = "black"
        break
    default:
        class1.style.backgroundColor = "#fefcdb66"
        class2.style.backgroundColor = "#fefcdb66"
        class3.style.backgroundColor = "#fefcdb66"
        class4.style.backgroundColor = "#fefcdb66"
        class5.style.backgroundColor = "#fefcdb66"
        class6.style.backgroundColor = "#fefcdb66"
        class7.style.backgroundColor = "#fefcdb66"
        class8.style.backgroundColor = "#fefcdb66"
        class9.style.backgroundColor = "#fefcdb66"
        class10.style.backgroundColor = "#fefcdb66"
        class11.style.backgroundColor = "#fefcdb66"
        class12.style.backgroundColor = "#fefcdb66"
        class13.style.backgroundColor = "#fefcdb66"
        class14.style.backgroundColor = "#fefcdb66"
        class15.style.backgroundColor = "#fefcdb66"
        class16.style.backgroundColor = "#fefcdb66"
        class17.style.backgroundColor = "#fefcdb66"
        class18.style.backgroundColor = "#fefcdb66"
        class19.style.backgroundColor = "#fefcdb66"
        class20.style.backgroundColor = "#fefcdb66"

        class1.style.color = "black"
        class2.style.color = "black"
        class3.style.color = "black"
        class4.style.color = "black"
        class5.style.color = "black"
        class6.style.color = "black"
        class7.style.color = "black"
        class8.style.color = "black"
        class9.style.color = "black"
        class10.style.color = "black"
        class11.style.color = "black"
        class12.style.color = "black"
        class13.style.color = "black"
        class14.style.color = "black"
        class15.style.color = "black"
        class16.style.color = "black"
        class17.style.color = "black"
        class18.style.color = "black"
        class19.style.color = "black"
        class20.style.color = "black"
        break
}